# Generated by Django 6.0.3 on 2026-03-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martillo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('CERRADA', 'Cerrada'), ('DESIERTA', 'Desierta')], default='ACTIVA', max_length=10),
        ),
        migrations.AddField(
            model_name='subasta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='subastas/'),
        ),
    ]
